[Desktop Entry]
Type=Service
X-KDE-ServiceTypes=PhononBackend
MimeType=application/x-annodex;video/quicktime;video/x-quicktime;audio/x-m4a;application/x-quicktimeplayer;video/mkv;video/msvideo;video/x-msvideo;video/x-flic;audio/x-aiff;audio/aiff;audio/x-pn-aiff;audio/x-realaudio;audio/basic;audio/x-basic;audio/x-pn-au;audio/x-8svx;audio/8svx;audio/x-16sv;audio/168sv;image/x-ilbm;image/ilbm;video/x-anim;video/anim;image/png;image/x-png;video/mng;video/x-mng;audio/x-ogg;audio/x-speex+ogg;application/ogg;application/ogg;audio/vnd.rn-realaudio;audio/x-pn-realaudio-plugin;audio/x-real-audio;application/vnd.rn-realmedia;video/mpeg;video/x-mpeg;audio/x-wav;audio/wav;audio/x-pn-wav;audio/x-pn-windows-acm;audio/mpeg2;audio/x-mpeg2;audio/mpeg3;audio/x-mpeg3;audio/mpeg;audio/x-mpeg;x-mpegurl;audio/x-mpegurl;audio/mp3;audio/mpeg;
X-KDE-Library=phonon_ds9
X-KDE-PhononBackendInfo-InterfaceVersion=1
X-KDE-PhononBackendInfo-Version=@PHONON_DS9_VERSION@
X-KDE-PhononBackendInfo-Website=http://qt.nokia.com/
InitialPreference=15

Name=DirectShow9
Name[bs]=DirectShow9
Name[ca]=DirectShow9
Name[ca@valencia]=DirectShow9
Name[cs]=DirectShow9
Name[da]=DirectShow9
Name[de]=DirectShow9
Name[el]=DirectShow9
Name[es]=DirectShow9
Name[et]=DirectShow9
Name[hu]=DirectShow9
Name[it]=DirectShow9
Name[nb]=DirectShow9
Name[nds]=DirectShow9
Name[nl]=DirectShow9
Name[pa]=ਡਾਇਰੈਕਟ-ਸ਼ੋ9
Name[pt]=DirectShow9
Name[pt_BR]=DirectShow9
Name[ro]=DirectShow9
Name[ru]=DirectShow9
Name[sr]=Дајректшоу‑9
Name[sr@ijekavian]=Дајректшоу‑9
Name[sr@ijekavianlatin]=DirectShow‑9
Name[sr@latin]=DirectShow‑9
Name[sv]=DirectShow 9
Name[ug]=DirectShow9
Name[uk]=DirectShow9
Name[x-test]=xxDirectShow9xx
Name[zh_CN]=DirectShow9
Name[zh_TW]=DirectShow9

Comment=Phonon DirectShow9 backend
Comment[bs]=DirectShow9 kao pozadina Phonona
Comment[ca]=Dorsal DirectShow9 del Phonon
Comment[ca@valencia]=Dorsal DirectShow9 del Phonon
Comment[cs]=Podpůrná vrstva DirectShow9 pro Phonon
Comment[da]=Phonon DirectShow9-motor
Comment[de]=Phonon-Treiber für DirectShow9
Comment[el]=Σύστημα υποστήριξης DirectShow9 του Phonon
Comment[es]=Motor DirectShow9 para Phonon
Comment[et]=Phononi DirectShow9 taustaprogramm
Comment[hu]=Phonon DirectShow9-modul
Comment[it]=Motore DirectShow9 di Phonon
Comment[nb]=Phonon-motor for DirectShow9
Comment[nds]=DirectShow9-Hülpprogramm för Phonon
Comment[nl]=DirectShow9-backend van Phonon
Comment[pa]=ਫੋਨੋਨ DirectShow9 ਬੈਕਐਂਡ
Comment[pt]=Infra-estrutura do DirectShow9 para o Phonon
Comment[pt_BR]=Infraestrutura do DirectShow9 para o Phonon
Comment[ro]=Suportul DirectShow9 pentru Phonon
Comment[ru]=Механизм DirectShow9 для Phonon
Comment[sr]=Дајректшоу‑9 као позадина Фонона
Comment[sr@ijekavian]=Дајректшоу‑9 као позадина Фонона
Comment[sr@ijekavianlatin]=DirectShow‑9 kao pozadina Phonona
Comment[sr@latin]=DirectShow‑9 kao pozadina Phonona
Comment[sv]=Phonon Directshow 9-gränssnitt
Comment[uk]=Модуль DirectShow9 для Phonon
Comment[x-test]=xxPhonon DirectShow9 backendxx
Comment[zh_CN]=Phonon DirectShow9 后端
Comment[zh_TW]=Phonon DirectShow9 後端介面
